### ISSUE TITLE
Google Drive Link?

### ISSUE THREAD

**Issue by SiftingSands** [qianyuzqy/TransVOD_Lite#1]
Could the checkpoint files (https://pan.baidu.com/s/1WAXRgXODX1tZ5PNkNOGDaA) be placed in a google drive? I think a lot of people like myself can't easily create a Baidu account to download the checkpoints. Thanks!

**Comment by qianyuzqy** [comment]
Hi, thanks for your interest in our work. 
I am very sorry that my VPN account has been blocked by the firewall, and I can't log into my Google Drive account now. I'll figure it out but it's gonna take some time. In the meantime, we suggest you download our checkpoints from Baidu Netdisk.

**Comment by SiftingSands** [comment]
Appreciate the rapid response! Understood on the firewall situation. I'll further look into getting it from Baidu Netdisk.

**Comment by Sairam13001** [comment]
@SiftingSands, Could you download from Baidu? I am trying to download but am facing some problems.
please let me know.

**Comment by qianyuzqy** [comment]
@Sairam13001 @SiftingSands Hello, thanks for your interest in our work.
We have uploaded all of the pre-trained models in this link: https://drive.google.com/drive/folders/1eqpiVLAWA_oPYiGmP6CW03WJlXVDjy6e?usp=share_link

**Comment by SiftingSands** [comment]
Thanks for taking the time to upload to google drive!

**Comment by Sairam13001** [comment]
Thank you for your time and effort.
