### ISSUE TITLE
About visualizing image

### ISSUE THREAD

**Issue by fisal-ITS** [qianyuzqy/TransVOD_Lite#13]
> It's okay @qianyuzqy, I figured it out. Thank you so much for your reply. I hope you get well soon. Take care.

Hai, Can you tell me how to visualize the image? I have got the code given by the author, but I got an error in running it.

_Originally posted by @fisal-ITS in https://github.com/qianyuzqy/TransVOD_Lite/issues/5#issuecomment-1546919747_

**Comment by returnlsz** [comment]
@fisal-ITS Can you also send me a copy of the visualization code of images and videos, my email is zifeng2001827@163.com, thanks!
