### ISSUE TITLE
Pre-trained weights 

### ISSUE THREAD

**Issue by adilsonmedronha** [qianyuzqy/TransVOD_Lite#3]
Can you please provide "TransVOD_Lite_pretrained_models" via Google Drive? 
Unable to download via Baidu...  Thanks in advance.

**Comment by qianyuzqy** [comment]
Thanks for your interest in our work.

As per your request, we have uploaded all of the pre-trained models in this link: https://drive.google.com/drive/folders/1eqpiVLAWA_oPYiGmP6CW03WJlXVDjy6e?usp=share_link
