### ISSUE TITLE
Pre-trained weights on google Drive 

### ISSUE THREAD

**Issue by goku-krish10** [qianyuzqy/TransVOD_Lite#4]
Thank you for making this code an open source for everyone so that we can experiment with the code.
I can not download the pre-trained weights from the Baidu Network as I don't find my country in the login registration.
Can you please provide this in google drive so that I can download it ?

**Comment by qianyuzqy** [comment]
Thanks for your interest in our work.

As per your request, we have uploaded all of the pre-trained models in this link: https://drive.google.com/drive/folders/1eqpiVLAWA_oPYiGmP6CW03WJlXVDjy6e?usp=share_link
