### ISSUE TITLE
ImportError on MSDA

### ISSUE THREAD

**Issue by fisal-ITS** [qianyuzqy/TransVOD_Lite#8]
I have an error when i tried to run 
`GPUS_PER_NODE=8 ./tools/run_dist_launch.sh $1 swinb $2 configs/swinb_train_single.sh`

it says :
`Traceback (most recent call last):
  File "test.py", line 18, in <module>
    from functions.ms_deform_attn_func import MSDeformAttnFunction, ms_deform_attn_core_pytorch
  File "/home/fisalaly/TransVOD_Lite/models/ops/functions/__init__.py", line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/home/fisalaly/TransVOD_Lite/models/ops/functions/ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: /home/fisalaly/TransVOD_Lite/models/ops/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv`

what i have done : 
1. I tried to reinstall mmcv-full (i found some solutions on Stackoverflow) but the error still exist
2. i tried to re-build MultiScaleDeformableAttention wtih `sh ./make.sh` , it says `MultiScaleDeformableAttention 1.0 is already the active version in easy-install.pth` . But when i tried to run `test.py` . the error showed up again

can anyone help me with this issue?

**Comment by qianyuzqy** [comment]
Hi@fisal-ITS , sorry for the late reply.

The reason for this error is that you did not successfully install MultiScaleDeformableAttention, which has nothing to do with the installation of MMCV. 

First, please check your installing environment and follow the instruction for the installation of MultiScaleDeformableAttention in Deformable DETR.

Then, I suggest that you need first uninstall MultiScaleDeformableAttention, including removing the files and reinstalling them again. If you don't rm -rf those files, the error could show up again.

Hope this could be helpful to you.

Thanks,
